In [1]:
import pandas as pd

books = pd.read_csv("books_with_categories.csv")

In [2]:
from transformers import pipeline
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = 0)
classifier("I love this!")

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/329M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/329M [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.00852869637310505},
  {'label': 'neutral', 'score': 0.0057645998895168304},
  {'label': 'anger', 'score': 0.0044197943061590195},
  {'label': 'sadness', 'score': 0.0020923942793160677},
  {'label': 'disgust', 'score': 0.001611993182450533},
  {'label': 'fear', 'score': 0.0004138525982853025}]]

In [3]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296023964881897},
  {'label': 'neutral', 'score': 0.14038582146167755},
  {'label': 'fear', 'score': 0.06816228479146957},
  {'label': 'joy', 'score': 0.047942496836185455},
  {'label': 'anger', 'score': 0.009156370535492897},
  {'label': 'disgust', 'score': 0.0026284740306437016},
  {'label': 'sadness', 'score': 0.0021221626084297895}],
 [{'label': 'neutral', 'score': 0.44937026500701904},
  {'label': 'disgust', 'score': 0.2735917270183563},
  {'label': 'joy', 'score': 0.10908300429582596},
  {'label': 'sadness', 'score': 0.09362746775150299},
  {'label': 'anger', 'score': 0.040478311479091644},
  {'label': 'surprise', 'score': 0.026970162987709045},
  {'label': 'fear', 'score': 0.006879050750285387}],
 [{'label': 'neutral', 'score': 0.6462153196334839},
  {'label': 'sadness', 'score': 0.24273386597633362},
  {'label': 'disgust', 'score': 0.043422769755125046},
  {'label': 'surprise', 'score': 0.028300585225224495},
  {'label': 'joy', 'score': 0.014211482368409634},
  {'label': 'fear', 'score': 0.014084112830460072},
  {'label': 'anger', 'score': 0.011031917296350002}],
 [{'label': 'fear', 'score': 0.9281682968139648},
  {'label': 'anger', 'score': 0.03219089284539223},
  {'label': 'neutral', 'score': 0.012808678671717644},
  {'label': 'sadness', 'score': 0.008756883442401886},
  {'label': 'surprise', 'score': 0.00859791412949562},
  {'label': 'disgust', 'score': 0.008431815542280674},
  {'label': 'joy', 'score': 0.0010455832816660404}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104157850146294},
  {'label': 'disgust', 'score': 0.006480602081865072},
  {'label': 'fear', 'score': 0.005393990781158209},
  {'label': 'surprise', 'score': 0.002286941045895219},
  {'label': 'anger', 'score': 0.0018428912153467536},
  {'label': 'joy', 'score': 0.0017338799079880118}],
 [{'label': 'joy', 'score': 0.9327985644340515},
  {'label': 'disgust', 'score': 0.03771667554974556},
  {'label': 'neutral', 'score': 0.0158917885273695},
  {'label': 'sadness', 'score': 0.006444466765969992},
  {'label': 'anger', 'score': 0.005024932790547609},
  {'label': 'surprise', 'score': 0.0015812050551176071},
  {'label': 'fear', 'score': 0.0005423033144325018}],
 [{'label': 'joy', 'score': 0.6528713703155518},
  {'label': 'neutral', 'score': 0.2542743384838104},
  {'label': 'surprise', 'score': 0.06808283925056458},
  {'label': 'sadness', 'score': 0.009908970445394516},
  {'label': 'disgust', 'score': 0.006512210238724947},
  {'label': 'anger', 'score': 0.004821299575269222},
  {'label': 'fear', 'score': 0.0035290103405714035}],
 [{'label': 'neutral', 'score': 0.549476683139801},
  {'label': 'sadness', 'score': 0.1116902157664299},
  {'label': 'disgust', 'score': 0.10400675237178802},
  {'label': 'surprise', 'score': 0.07876547425985336},
  {'label': 'anger', 'score': 0.0641336590051651},
  {'label': 'fear', 'score': 0.05136283487081528},
  {'label': 'joy', 'score': 0.04056442901492119}]]

In [4]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [5]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.009156370535492897},
 {'label': 'disgust', 'score': 0.0026284740306437016},
 {'label': 'fear', 'score': 0.06816228479146957},
 {'label': 'joy', 'score': 0.047942496836185455},
 {'label': 'neutral', 'score': 0.14038582146167755},
 {'label': 'sadness', 'score': 0.0021221626084297895},
 {'label': 'surprise', 'score': 0.7296023964881897}]

In [11]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [12]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [13]:
from tqdm import tqdm

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [06:48<00:00, 12.72it/s]

In [14]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [15]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,isbn13
0,0.064134,0.273592,0.928168,0.932799,0.646215,0.967158,9780002005883
1,0.612620,0.348285,0.942528,0.704422,0.887939,0.111690,9780002261982
2,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,9780006178736
3,0.351485,0.150722,0.360706,0.251881,0.732685,0.111690,9780006280897
4,0.081412,0.184496,0.095043,0.040564,0.884389,0.475880,9780006280934
...,...,...,...,...,...,...,...
5192,0.148209,0.030643,0.919165,0.255171,0.853721,0.980877,9788172235222
5193,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,9788173031014
5194,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,9788179921623
5195,0.064134,0.104007,0.459269,0.759457,0.951104,0.368111,9788185300535
5196,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,9789027712059

In [16]:
books = pd.merge(books, emotions_df, on ="isbn13")

In [17]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273592,0.928168,0.932799,0.646215,0.967158
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612620,0.348285,0.942528,0.704422,0.887939,0.111690
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction,0.351485,0.150722,0.360706,0.251881,0.732685,0.111690
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction,0.081412,0.184496,0.095043,0.040564,0.884389,0.475880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction,0.148209,0.030643,0.919165,0.255171,0.853721,0.980877
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction,0.064134,0.104007,0.459269,0.759457,0.951104,0.368111
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690

In [18]:
books.to_csv("books_with_emotions.csv", index = False)